# Generated by Django 3.1.2 on 2020-12-08 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_listing',
            old_name='cover_letter_required',
            new_name='requires_additional_documents',
        ),
        migrations.RemoveField(
            model_name='job_listing',
            name='gpa',
        ),
        migrations.RemoveField(
            model_name='job_listing',
            name='job_street_address',
        ),
        migrations.RemoveField(
            model_name='job_listing',
            name='letter_of_reccomendation',
        ),
        migrations.RemoveField(
            model_name='job_listing',
            name='transcript_required',
        ),
    ]
