# Generated by Django 3.1.2 on 2020-12-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_listing',
            name='job_description',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='job_listing',
            name='job_wage_range',
            field=models.CharField(choices=[('state minimum hourly wage', 'State Minimum Hourly Wage'), ('<10k', 'Less than 10K Yearly'), ('10-19k yearly', '10-19K Yearly'), ('20k-39k yearly', '20k-39K Yearly'), ('40k-64k yearly', '40k-64K Yearly'), ('65k-70k yearly', '65k-70K Yearly'), ('70-99k yearly', '70-99K Yearly'), ('100k+', '100K+'), ('undisclosed', 'Undisclosed')], default='state minimum hourly wage', max_length=50),
        ),
        migrations.AlterField(
            model_name='job_listing',
            name='listing_description',
            field=models.CharField(max_length=255),
        ),
    ]
