# Generated by Django 3.1.2 on 2020-12-07 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20201205_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_listing',
            name='employer_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='listings.employer'),
            preserve_default=False,
        ),
    ]
