# Generated by Django 3.1.2 on 2020-12-08 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20201208_0758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='applicant_skill',
            old_name='Applicant_id',
            new_name='applicanta',
        ),
        migrations.RenameField(
            model_name='applicant_skill',
            old_name='skill_id',
            new_name='skill',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='Applicant_id',
            new_name='applicant',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='job_listing_id',
            new_name='job_listing',
        ),
        migrations.RenameField(
            model_name='employer',
            old_name='size_id',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='employer',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='job_listing',
            old_name='employer_id',
            new_name='employer',
        ),
        migrations.RenameField(
            model_name='job_listing',
            old_name='job_type_id',
            new_name='job_type',
        ),
        migrations.RenameField(
            model_name='job_skill',
            old_name='job_listing_id',
            new_name='job_listing',
        ),
    ]
