# Generated by Django 3.1.2 on 2020-12-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_job_listing_employer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_listing',
            name='job_link_to_application',
            field=models.CharField(default='https://search.amazondelivers.jobs/job/salt-lake-city/delivery-station-liaison-part-time-20-29-hrs-dut3-salt-lake-city-ut-usa/3413/18162908', max_length=255),
            preserve_default=False,
        ),
    ]
