# Generated by Django 3.1.2 on 2020-12-08 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20201208_0807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant_skill',
            old_name='applicanta',
            new_name='applicant',
        ),
        migrations.RenameField(
            model_name='job_skill',
            old_name='skill_id',
            new_name='skill',
        ),
    ]
