# Generated by Django 3.1.2 on 2020-12-07 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_job_listing_job_link_to_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_listing',
            name='employer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer', to='listings.employer'),
        ),
        migrations.AlterField(
            model_name='job_listing',
            name='job_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='listings.job_type'),
        ),
    ]
